server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reactive_services
    username: postgres
    password: postgres
spring.r2dbc:
  pool:
    initial-size: 100
    max-size: 500
    max-idle-time: 30m
    validation-query: SELECT 1